"""add_task_reviews_table

Revision ID: 08deb19fab7e
Revises: 3a7f1c2d4e5f
Create Date: 2026-07-10 10:12:20.087346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08deb19fab7e'
down_revision: Union[str, None] = '3a7f1c2d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_chunk', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reviews_task_id'), 'task_reviews', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_reviews_user_id'), 'task_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_reviews_user_id'), table_name='task_reviews')
    op.drop_index(op.f('ix_task_reviews_task_id'), table_name='task_reviews')
    op.drop_table('task_reviews')
    # ### end Alembic commands ###
