"""add_standard_to_style_templates

Revision ID: 820ed49c4fca
Revises: 5e132870e319
Create Date: 2026-07-08 16:06:52.855365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820ed49c4fca'
down_revision: Union[str, None] = '5e132870e319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_templates', sa.Column('standard', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_style_templates_standard'), 'style_templates', ['standard'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_templates_standard'), table_name='style_templates')
    op.drop_column('style_templates', 'standard')
    # ### end Alembic commands ###
